services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - backend-network
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecret

  api:
    build: api
    networks:
      - frontend-network
      - backend-network
    ports:
      - "8080:8080"

networks:
  backend-network:
  frontend-network: